name: flutter_page_tranzitionz_example
description: flutter_page_tranzitionz example app.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_page_tranzitionz:
    # When depending on this package from a real application you should use:
    #   flutter_page_tranzitionz: ^x.y.z
    path: ../

dev_dependencies:
  dart_lintz: 1.2.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
