name: flutter_page_tranzitionz_example
description: flutter_page_tranzitionz example app.
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_page_tranzitionz:
    # When depending on this package from a real application you should use:
    #   flutter_page_tranzitionz: ^x.y.z
    path: ../

dev_dependencies:
  dart_lintz: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
