name: flutter_page_tranzitionz
description: A set of Page Route Transitions for simple and easy animations between different screens. Inspired by other packages on pub.dev.
version: 2.1.1
repository: https://github.com/mj12358/flutter-page-tranzitionz
funding:
  - https://www.buymeacoffee.com/mj12358
topics:
  - flutter
  - animation
  - transition

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_lintz: ^1.2.1
  flutter_test:
    sdk: flutter
